Assignment2/Controllers/AccountantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Assignment2.Helpers;
using Assignment2.Models;
using System.Net;
using System.Data.Entity;
using Assignment2.Data_Access_Layer;

namespace Assignment2.Controllers
{
    [Authorize(Roles = Roles.ACCOUNTANT)]
    public class AccountantController : Controller
    {
        private readonly IUsersHelper userhelper = new UsersHelper();
        private readonly IReportHelper reportHelper = new ReportHelper();
        public AccountantController(IUsersHelper _userHelper)
        {
            userhelper = _userHelper;
        }
        public AccountantController()
        {

        }

        // GET: Accountant
        public ActionResult Index()
        {
            return View();
        }


        /// <summary>
        /// This method is used to navigation for accountant user
        /// </summary>
        /// <returns>view</returns>
        [HttpPost]
        public ActionResult Index(string Button)
        {
            if (Button.Equals("List of Users"))
            {
                return RedirectToAction("ListOfUsers");
            }
            else if (Button.Equals("Total Costs By Engineer Report"))
            {
                return RedirectToAction("TotalCostsByEngineerReport");
            }
            else if (Button.Equals("Average Costs By Engineer Report"))
            {
                return RedirectToAction("AverageCostsByEngineerReport");
            }
            else if (Button.Equals("Costs By District Report"))
            {
                return RedirectToAction("CostsByDistrictReport");
            }
            else if (Button.Equals("Monthly Costs For District Report"))
            {
                return RedirectToAction("MonthlyCostsForDistrictReport");
            }
            return View();
        }

        /// <summary>
        /// This method is used to view all users list 
        /// </summary>
        /// <returns>view</returns>
        public ActionResult ListOfUsers()
        {
            IList<UserViewModel> viewModel = new List<UserViewModel>();
            try
            {
                viewModel = userhelper.ListOfUsers();

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex);
            }
            return View(viewModel);
        }


        /// <summary>
        /// This method is used to view user detail for change district
        /// </summary>
        /// <returns>view</returns>
        public ActionResult ChangeDistrictForUsers(string userId)
        {
            if (userId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserViewModel userDetail = userhelper.GetUserData(userId);
            if (userDetail == null)
            {
                return HttpNotFound();
            }
            var districtList = userhelper.GetDistrictList();
            ViewBag.District = new SelectList(districtList);
            return View(userDetail);
        }

        /// <summary>
        /// This method is used to update user detail for change district
        /// </summary>
        /// <returns>view</returns>
        [HttpPost]
        public ActionResult ChangeDistrictForUsers(UserViewModel UserViewModel)
        {
            var districtList = userhelper.GetDistrictList();

            try
            {
               
                if (ModelState.IsValid)
                {
                    ViewBag.District = new SelectList(districtList);
                    userhelper.UpdateDistrictForUser(UserViewModel.UserId, UserViewModel.District);
                    ModelState.AddModelError("success", "The District has been changed!!");
                }
            }

            catch (Exception ex)
            {
                ViewBag.District = new SelectList(districtList);
                ModelState.AddModelError("", ex.Message);
            }
            return View(UserViewModel);
        }


        /// <summary>
        /// This method is used to view total costs by engineer report
        /// </summary>
        /// <returns>view</returns>
        public ActionResult TotalCostsByEngineerReport()
        {
            IList<TotalCostsByEngineerModel> viewModel = new List<TotalCostsByEngineerModel>();
            try
            {
                viewModel = reportHelper.TotalCostsByEngineerView();

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex);
            }
            return View(viewModel);
        }

        /// <summary>
        /// This method is used to view average costs by engineer report
        /// </summary>
        /// <returns>view</returns>
        public ActionResult AverageCostsByEngineerReport()
        {
            IList<AverageCostsByEngineerModel> viewModel = new List<AverageCostsByEngineerModel>();
            try
            {
                viewModel = reportHelper.AverageCostsByEngineerView();

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex);
            }
            return View(viewModel);
        }

        /// <summary>
        /// This method is used to view costs by district report
        /// </summary>
        /// <returns>view</returns>
        public ActionResult CostsByDistrictReport()
        {
            IList<CostsByDistrictModel> viewModel = new List<CostsByDistrictModel>();
            try
            {
                viewModel = reportHelper.CostsByDistrictView();

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex);
            }
            return View(viewModel);
        }

        /// <summary>
        /// This method is used to view monthly costs for district report
        /// </summary>
        /// <returns>view</returns>
        public ActionResult MonthlyCostsForDistrictReport()
        {
            var Users = new UsersHelper();
            var districtList = Users.GetDistrictList();
            ViewBag.District = new SelectList(districtList);
            IList<MonthlyCostsForDistrictModel> viewModel = new List<MonthlyCostsForDistrictModel>();
            return View(viewModel);
        }

        /// <summary>
        /// This method is used to view monthly costs for district report based on search
        /// </summary>
        /// <returns>view</returns>
        [HttpPost]
        public ActionResult MonthlyCostsForDistrictReport(FormCollection fc, string district)
        {
            var Users = new UsersHelper();
            var districtList = Users.GetDistrictList();
            ViewBag.District = new SelectList(districtList);
            IList<MonthlyCostsForDistrictModel> viewModel = new List<MonthlyCostsForDistrictModel>();
            try
            {
                viewModel = reportHelper.MonthlyCostsForDistrictView(district);

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex);
            }
            return View(viewModel);
        }
    }
}

Assignment2/Views/Accountant/AverageCostsByEngineerReport.cshtml
@model IEnumerable<Assignment2.Models.AverageCostsByEngineerModel>

@{
    ViewBag.Title = "Average Costs By Engineer Report";
}

<h2>Average Costs By Engineer Report</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AverageHours)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AverageCosts)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoleName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AverageHours)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AverageCosts)
        </td>
    </tr>
}

</table>

Assignment2/Views/Accountant/ChangeDisTrictForUsers.cshtml
@model Assignment2.Models.UserViewModel

@{
    ViewBag.Title = "ChangeDistrict";
}

<h2>Change District For Users</h2>
<hr>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        @Html.ValidationMessage("success", new { @class = "text-success" })
        @Html.ValidationSummary(true, "", new { @class = "text-success" })
        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.UserName)
        @Html.HiddenFor(model => model.RoleName)
        @Html.HiddenFor(model => model.MaximumCost)
        @Html.HiddenFor(model => model.MaximumHours)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.RoleName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaximumCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.MaximumCost, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaximumHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.MaximumHours, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.District, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.District, null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Change District" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListOfUsers")
</div>

Assignment2/Views/Accountant/CostsByDistrictReport.cshtml
@model IEnumerable<Assignment2.Models.CostsByDistrictModel>

@{
    ViewBag.Title = "Costs By District Report";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DistrictName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hours)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Costs)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DistrictName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hours)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Costs)
        </td>
    </tr>
}

</table>

Assignment2/Views/Accountant/Index.cshtml
@{
    ViewBag.Title = "Accountant Home Page";
}

<p>
    <h2>@ViewBag.Title</h2>
</p>
@using (Html.BeginForm("Index", "Accountant", FormMethod.Post, new { id = "submitForm" }))
{   <hr />
    <p>
        <button id="ButtonUsersView" name="Button" style="width:400px" value="List of Users">List of Users </button>
    </p>
    <p>
        <button id="TotalCostsByEngineerReport" name="Button" style="width:400px" value="Total Costs By Engineer Report">Total Costs By Engineer Report </button>
    </p>
    <p>
        <button id="AverageCostsByEngineerReport" name="Button" style="width:400px" value="Average Costs By Engineer Report">Average Costs By Engineer Report </button>
    </p>
    <p>
        <button id="CostsByDistrictReport" name="Button" style="width:400px" value="Costs By District Report">Costs By District Report </button>
    </p>
    <p>
        <button id="MonthlyCostsForDistrictReport" name="Button" style="width:400px" value="Monthly Costs For District Report">Monthly Costs For District Report </button>
    </p>
    <p>
        &nbsp;
    </p>
}

Assignment2/Views/Accountant/ListOfUsers.cshtml
@model IEnumerable<Assignment2.Models.UserViewModel>

@{
    ViewBag.Title = "ListOfUsers";
}

<h2>Users List</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaximumCost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaximumHours)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.District)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoleName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaximumCost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaximumHours)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.District)
        </td>
        <td>
            @Html.ActionLink("Change District", "ChangeDistrictForUsers", new { userId = item.UserId })
        </td>
    </tr>
}

</table>

Assignment2/Views/Accountant/MonthlyCostsForDistrictReport.cshtml
@model IEnumerable<Assignment2.Models.MonthlyCostsForDistrictModel>

@{
    ViewBag.Title = "Monthly Costs For District Report";
}

<h2>Monthly Costs For District Report</h2>


    @using (Html.BeginForm())
    {
<p>
    Title: @Html.DropDownList("District")  <input type="submit" value="Search" />
</p>
    }

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Month)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MonthlyHours)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MonthlyCosts)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Month)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MonthlyHours)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MonthlyCosts)
                </td>
            </tr>
        }

    </table>

Assignment2/Views/Accountant/TotalCostsByEngineerReport.cshtml
@model IEnumerable<Assignment2.Models.TotalCostsByEngineerModel>

@{
    ViewBag.Title = "Total Costs By Engineer Report";
}

<h2>@ViewBag.Title</h2>
<hr />
<p>
    
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalHours)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalCosts)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoleName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalHours)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalCosts)
        </td>
    </tr>
}

</table>