Assignment2/Models/ManagerViewModel.cs
//using System;
//using System.ComponentModel.DataAnnotations;

//namespace Assignment2.Models
//{
//    public class ListInterventionViewModel
    
//    {
           
//            [Display(Name = "Client District")]
//            public string ClientDistrict { get; set; }
//            [Display(Name = "Client Name")]
//            public string ClientName { get; set; }
//            [Display(Name = "Intervention Type Name")]
//            public string InterventionTypeName { get; set; }
//            [Display(Name = "Intervention Cost")]
//            public decimal InterventionCost { get; set; }
//            [Display(Name = "Intervention Hours")]
//            public decimal InterventionHours { get; set; }
//            [Display(Name = "Create Date")]
//            public DateTime CreateDate { get; set; }
//            public string Status { get; set; }
//            [Display(Name = "Intervention Id")]
//            public int InterventionId { get; set; }

//        }
//    }

Assignment2/Controllers/ManagerController.cs
using Assignment2.Helpers;
using Assignment2.Models;
using System;
using System.Web.Mvc;
using Assignment2.Models.Database_Models;
using System.Collections.Generic;
using System.Net;
using WebApplication2.Exceptions;

namespace Assignment2.Controllers
{
    [Authorize(Roles = Roles.MANAGER)]
    public class ManagerController : Controller
    {
        private readonly IManagerHelper managerHelper = new ManagerHelper();
        public ManagerController(IManagerHelper _managerHelper)
        {
            managerHelper = _managerHelper;
        }
        public ManagerController()
        {
            
        }

        // GET: Manager
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string Button)
        {
            return RedirectToAction(Button);
        }
        /// <summary>
        /// This action method is used retruns a list of interventions manager needs to approve or cancel
        /// </summary>
        /// <returns>View</returns>
        public ActionResult ListOfInterventions()
        {
            IList<ListInterventionViewModel> viewModel = new List<ListInterventionViewModel>();
            try
            {
                viewModel = managerHelper.GetListOfProposedInterventions();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex);
            }

            return View(viewModel);
        }
        /// <summary>
        /// This action method is used retruns a views for editing intervention
        /// </summary>
        /// <returns>View</returns>
        public ActionResult EditIntervention(int interventionId)
        {
            ListInterventionViewModel viewModel = new ListInterventionViewModel();
            try
            {
                viewModel = managerHelper.GetIntervention(interventionId);
                var statuslist = managerHelper.GetPossibleStatusUpdateForIntervention(viewModel.Status);
                ViewBag.Status = new SelectList(statuslist);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex);
            }

            return View(viewModel);
        }

        /// <summary>
        /// This action method is used post edit to intervention and returns the changed intervention data.
        /// </summary>
        /// <returns>View</returns>
        [HttpPost]
        public ActionResult EditIntervention(ListInterventionViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var intervention = managerHelper.UpdateInterventionStatus(viewModel.InterventionId, viewModel.Status);
                    var statuslist = managerHelper.GetPossibleStatusUpdateForIntervention(viewModel.Status);
                    ViewBag.Status = new SelectList(statuslist);
                    ModelState.AddModelError("success", "Intervention Updated Successfully");
                }
                catch (Exception ex)
                {
                    ViewBag.Status = new SelectList(new List<string>() { viewModel.Status });
                    ModelState.AddModelError("alert", ex.Message);
                }
             
            }
            return View(viewModel);
            
        }
        /// <summary>
        /// This action method is used retruns a list of interventions manager as approved at any time.
        /// </summary>
        /// <returns>View</returns>
        public ActionResult ListOfAssociatedInterventions()
        {
            IList<ListInterventionViewModel> viewModel = new List<ListInterventionViewModel>();
            try
            {
                viewModel = managerHelper.GetAssociatedIntervention_ForManager();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex);
            }

            return View(viewModel);
        }
    }
}

Assignment2/Views/Manager/EditIntervention.cshtml
@model Assignment2.Models.ListInterventionViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Intervention</h4>
        <hr />
        @Html.ValidationMessage("success", new { @class = "text-success" })
        @Html.ValidationMessage("alert", new { @class = "text-danger" })

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.InterventionId)
        @Html.HiddenFor(model => model.ClientDistrict)
        @Html.HiddenFor(model => model.ClientName)
        @Html.HiddenFor(model => model.Condition)
        @Html.HiddenFor(model => model.CreateDate)
        @Html.HiddenFor(model => model.InterventionCost)
        @Html.HiddenFor(model => model.InterventionHours)
        @Html.HiddenFor(model => model.InterventionTypeName)
        @Html.HiddenFor(model => model.ModifyDate)

        <div class="form-group">
            @Html.LabelFor(model => model.ClientDistrict, "Client District", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.ClientDistrict, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientName, "Client Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.ClientName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InterventionTypeName, "Intervention Type Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.InterventionTypeName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InterventionCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.InterventionCost, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InterventionHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.InterventionHours, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Status, null , htmlAttributes: new { @class = "form-control" })

            </div>
        </div>

    </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>

}

<div>
    @Html.ActionLink("Back to List", "ListOfInterventions")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Assignment2/Views/Manager/Index.cshtml
@{
    ViewBag.Title = "Manager Home Page";
    
}
<p>
    <h2>@ViewBag.Title</h2>
</p>
@using (Html.BeginForm("Index", "Manager", FormMethod.Post, new { id = "submitForm" }))
{<hr />
    <p>
        <button id="ButtonCreateNewClient" name="Button" style="width:400px" value="ListOfInterventions">List of Intervention to approve or cancel in your district</button>
    </p>
    <p>
        <button id="ButtonCreateIntervention" name="Button" style="width:400px" value="ListOfAssociatedInterventions">List of associated Interevntions</button>
    </p>
    
    
}

Assignment2/Views/Manager/ListOfAssociatedInterventions.cshtml
@using Assignment2.Models
@using Assignment2
@model IEnumerable<ListInterventionViewModel>

@{
    ViewBag.Title = "List Of Associated Interventions";
}

<h2>List Of Associated Interventions</h2>
@if (Model.Any())
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClientName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClientDistrict)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InterventionTypeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InterventionCost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InterventionHours)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)

            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <th>
                    @Html.DisplayFor(modelItem => item.ClientName)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.ClientDistrict)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.InterventionTypeName)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.InterventionCost)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.InterventionHours)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.CreateDate)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.Status)
                </th>
            </tr>
        }
    </table>
}
else
{
    <hr />
    <div> <h3>You have no interventions associated with you yet</h3> </div>
}

Assignment2/Views/Manager/ListOfInterventions.cshtml
@using Assignment2.Models
@using Assignment2
@model IEnumerable<ListInterventionViewModel>

@{
    ViewBag.Title = "List of Intervention to approve or cancel in your district";
}

<h2>List of Intervention to approve or cancel in your district</h2>

@if (Model.Any())
{ 
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClientName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClientDistrict)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InterventionTypeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InterventionCost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InterventionHours)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
                    
            </th>
            <th></th>
        </tr>
            
        @foreach (var item in Model)
        {
            <tr>
                <th>
                    @Html.DisplayFor(modelItem => item.ClientName)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.ClientDistrict)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.InterventionTypeName)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.InterventionCost)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.InterventionHours)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.CreateDate)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => item.Status)
                </th>
                <th>
                    @Html.ActionLink("Approve/Cancel", "EditIntervention", new { interventionId = item.InterventionId })   
                </th>
            </tr>
        }
    </table>
}
else
{
    <hr/>
    <div> <h3>You have no interventions to approve or cancel</h3> </div>
}